[versions]
accompanistSystemuicontroller = "0.36.0"
activityCompose = "1.12.3"
androidxComposeBom = "2026.01.01"
appcompat = "1.7.1"
compileSdk = "36"
minSdk = "28"
targetSdk = "36"
constraintLayout = "2.2.1"
coreKtx = "1.17.0"
compose = "1.10.2"
daggerHilt = "2.59.1"
espressoCore = "3.7.0"
fragmentKtx = "1.8.9"
junit = "4.13.2"
lifecycleKtx = "2.10.0"
material = "1.13.0"
navigation = "2.9.7"
testExtJunit = "1.3.0"
firebaseBom = "34.9.0"
agp = "9.0.0"
kotlin = "2.3.10"
ksp = "2.3.2"
room = "2.8.4"
coil = "3.3.0"
hiltNavigationCompose = "1.3.0"
datastore = "1.2.0"
kizitonwoseCalendar = "2.10.0"
material3 = "1.4.0"
googleServices = "4.4.4"


[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidxAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidxMaterial = { module = "com.google.android.material:material", version.ref = "material" }
composeLiveData = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
daggerHilt = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
daggerHiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "daggerHilt" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
junit = { module = "junit:junit", version.ref = "junit" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
material3 = { module = "androidx.compose.material3:material3" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
testExtJunit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
lifecycleKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version = "navigation" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
kizitonwose-calendar-compose = { module = "com.kizitonwose.calendar:compose", version.ref = "kizitonwoseCalendar" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }